# $OpenBSD$

COMMENT =	File identification library for Python

MODPY_EGG_VERSION =	2.2.8

DISTNAME =	identify-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/pre-commit/identify

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =	${MODPY_DEFAULT_VERSION_3}

RUN_DEPENDS =		pypi/py-editdistance-s

.include <bsd.port.mk>
