# $OpenBSD$

COMMENT =	tools to supplement packaging Python releases

MODPY_EGG_VERSION =	8.2.1

DISTNAME =	jaraco.packaging-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/jaraco/jaraco.packaging

# license field not set, consider bugging module's author
PERMIT_PACKAGE =	unknown license
PERMIT_DISTFILES =	unknown license

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =	${MODPY_DEFAULT_VERSION_3}

.include <bsd.port.mk>
