# $OpenBSD$

COMMENT =	Node.js virtual environment builder

MODPY_EGG_VERSION =	1.6.0

DISTNAME =	nodeenv-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/ekalinin/nodeenv

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

FLAVORS =	python3
FLAVOR ?=	python3

.include <bsd.port.mk>
