# $OpenBSD$

COMMENT =	Browser-based frontend to gdb. Debug C, C++, Go, or Rust

MODPY_EGG_VERSION =	0.14.0.2

DISTNAME =	gdbgui-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/cs01/gdbgui

# unknown license -> 'License :: GNU GPLv3'
PERMIT_PACKAGE =	unknown license
PERMIT_DISTFILES =	unknown license

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =	${MODPY_DEFAULT_VERSION_3}

.include <bsd.port.mk>
