# $OpenBSD$

COMMENT =		footprint modules for Kicad 5.1.0
V =			5.1.0
DISTNAME =		kicad-footprints-${V}
CATEGORIES =		cad

HOMEPAGE =		https://github.com/KiCad/kicad-footprints

MASTER_SITES =		https://github.com/KiCad/kicad-footprints/archive/${V}/

#CCA4
PERMIT_PACKAGE_CDROM =	Yes

DIST_SUBDIR =		kicad

MODULES =		devel/cmake

.include <bsd.port.mk>
