# $OpenBSD$

V =			5.1.4
COMMENT =		footprint modules for Kicad ${V}
DISTNAME =		kicad-footprints-${V}
CATEGORIES =		cad

HOMEPAGE =		https://github.com/KiCad/kicad-footprints

MASTER_SITES =		https://github.com/KiCad/kicad-footprints/archive/${V}/

#CCA4
PERMIT_PACKAGE =	Yes

COMPILER =		ports-clang

MODULES =		devel/cmake

.include <bsd.port.mk>
