# $OpenBSD: $

V =			0.6.4
COMMENT =		generate gcode from 2D or 3D models for 3-axis CNC

PKGNAME =		pycam-${V}

GH_ACCOUNT =		SebKuzminsky
GH_PROJECT =		pycam
GH_TAGNAME =		v${V}

CATEGORIES =		cad

HOMEPAGE =		http://pycam.sourceforge.net/

MAINTAINER =		Tracey Emery <tracey@openbsd.org>

#GPLv3
PERMIT_PACKAGE = 	Yes

MODULES =		lang/python

MODPY_SETUPTOOLS =	Yes

RUN_DEPENDS =		x11/py-gtk2

FLAVORS =		python3
FLAVOR =		python3

.include <bsd.port.mk>
