# $OpenBSD$

V =			5.1.4
COMMENT =		templates for Kicad ${V}
DISTNAME =		kicad-templates-${V}
CATEGORIES =		cad

HOMEPAGE =		https://github.com/KiCad/kicad-templates

MASTER_SITES =		https://github.com/KiCad/kicad-templates/archive/${V}/

#CCA4
PERMIT_PACKAGE =	Yes

COMPILER =		ports-clang

MODULES =		devel/cmake

.include <bsd.port.mk>
