# $OpenBSD$

COMMENT =		templates for Kicad 5.0.0
V =			5.0.0
DISTNAME =		kicad-templates-${V}
CATEGORIES =		cad

HOMEPAGE =		https://github.com/KiCad/kicad-templates

MASTER_SITES =		https://github.com/KiCad/kicad-templates/archive/${V}/

#CCA4
PERMIT_PACKAGE_CDROM =	Yes

DIST_SUBDIR =		kicad

MODULES =		devel/cmake

.include <bsd.port.mk>
