# $OpenBSD$

COMMENT =	fork of Python 2 and 3 ast modules with type comment support

MODPY_EGG_VERSION =	1.4.3

DISTNAME =	typed_ast-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/python/typed_ast

# Apache 2.0
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =	${MODPY_DEFAULT_VERSION_3}

.include <bsd.port.mk>
