# $OpenBSD: $
COMMENT =	portable cross 6809 assembler

DISTNAME =	asm6809-2.12
CATEGORIES =	devel

HOMEPAGE =	https://www.6809.org.uk/asm6809/

# GPLv3+
PERMIT_PACKAGE = Yes

WANTLIB += c

MASTER_SITES =	https://www.6809.org.uk/asm6809/dl/

CONFIGURE_STYLE = gnu

.include <bsd.port.mk>
