# $OpenBSD$

COMMENT =	The bidirectional mapping library for Python

MODPY_EGG_VERSION =	0.21.2

DISTNAME =	bidict-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://bidict.readthedocs.io

# unknown license -> 'MPL 2.0'
PERMIT_PACKAGE =	unknown license
PERMIT_DISTFILES =	unknown license

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =	${MODPY_DEFAULT_VERSION_3}

.include <bsd.port.mk>
