# $OpenBSD$

COMMENT =	Socket.IO integration for Flask applications

MODPY_EGG_VERSION =	5.1.0

DISTNAME =	Flask-SocketIO-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME:L}

CATEGORIES =	pypi

HOMEPAGE =	http://github.com/miguelgrinberg/Flask-SocketIO/

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =	${MODPY_DEFAULT_VERSION_3}

.include <bsd.port.mk>
