# $OpenBSD$
COMMENT=	open source video editing software

V=		19.12.0
DISTNAME=	kdenlive-v${V}
CATEGORIES=	multimedia
HOMEPAGE=	https://kdenlive.org
MASTER_SITES=	https://invent.kde.org/kde/kdenlive/-/archive/v${V}/

#GPLv2
PERMIT_PACKAGE=	Yes

MODULES=	devel/cmake

NO_TEST=	Yes

.include <bsd.port.mk>
