# $OpenBSD$

COMMENT =	Fast implementation of the edit distance (Levenshtein

MODPY_EGG_VERSION =	1.0.0

DISTNAME =	editdistance_s-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://www.github.com/asottile/editdistance-s

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =	${MODPY_DEFAULT_VERSION_3}

.include <bsd.port.mk>
