# $OpenBSD$

COMMENT =		massdrop keyboard firmware loader

GH_ACCOUNT =		Massdrop
GH_PROJECT =		mdloader
GH_TAGNAME =		1.0.3

PKGNAME =		mdloader-${GH_TAGNAME}

CATEGORIES =		sysutils

#GPLv3, SAM Software Package License
PERMIT_PACKAGE =	Yes

USE_GMAKE =		Yes
NO_TEST =		Yes

.include <bsd.port.mk>
