# $OpenBSD$

COMMENT =	hjson, a user interface for JSON

MODPY_EGG_VERSION =	3.0.1

DISTNAME =	hjson-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	devel

HOMEPAGE =	http://github.com/hjson/hjson-py

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
