# $OpenBSD$

COMMENT =		library modules for Kicad 4.0.x
V =			4.0.7
DISTNAME =		kicad-library-${V}
CATEGORIES =		cad

HOMEPAGE =		https://github.com/KiCad/kicad-library

MASTER_SITES =		https://github.com/KiCad/kicad-library/archive/${V}/

#CCA4
PERMIT_PACKAGE_CDROM =	Yes

DIST_SUBDIR =		kicad

MODULES =		devel/cmake

.include <bsd.port.mk>
