# $OpenBSD$
# for ESP32 https://www.esp32.com/viewtopic.php?t=7400
SUBDIR=
SUBDIR+= binutils
SUBDIR+= gcc-esp32
SUBDIR+= gcc-esp32-bootstrap
#SUBDIR+= gdb
SUBDIR+= newlib

.include <bsd.port.subdir.mk>
