# $OpenBSD: $

COMMENT =	sgmls and nsgmls parsers

HOMEPAGE =	https://metacpan.org/release/RAAB/SGMLSpm-1.1

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	SGMLSpm-1.1
CATEGORIES =	devel

# Perl
PERMIT_PACKAGE =		Yes

CPAN_AUTHOR =	RAAB

.include <bsd.port.mk>
