# $OpenBSD:$

COMMENT=	apache OFBIZ enterprise resource planning system

V=		18.12

GH_ACCOUNT =	apache
GH_PROJECT =	ofbiz-framework
GH_TAGNAME =	release${V}

PKGNAME =	${GH_ACCOUNT}-${GH_PROJECT:L}

CATEGORIES=	www net

HOMEPAGE=	https://ofbiz.apache.org

# Apache 2.0
PERMIT_PACKAGE=	Yes

NO_TEST=	Yes

BUILD_DEPENDS=	devel/jdk/11

.include <bsd.port.mk>
