# $OpenBSD$

COMMENT =	framework for managing and maintaining multi-language

MODPY_EGG_VERSION =	2.13.0

DISTNAME =	pre_commit-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/pre-commit/pre-commit

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =	${MODPY_DEFAULT_VERSION_3}

.include <bsd.port.mk>
