# $OpenBSD$

COMMENT =	Pure-Python Reed Solomon encoder/decoder

MODPY_EGG_VERSION =	1.5.4

DISTNAME =	reedsolo-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/tomerfiliba/reedsolomon

# unknown license -> 'Public Domain'
PERMIT_PACKAGE =	unknown license
PERMIT_DISTFILES =	unknown license

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

FLAVORS =	python3
FLAVOR ?=	python3

.include <bsd.port.mk>
