# $OpenBSD$

COMMENT =	Docutils -- Python Documentation Utilities

MODPY_EGG_VERSION =	0.17.1

DISTNAME =	docutils-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	http://docutils.sourceforge.net/

# unknown license -> 'public domain, Python, 2-Clause BSD, GPL 3 (see COPYING.txt)'
PERMIT_PACKAGE =	unknown license
PERMIT_DISTFILES =	unknown license

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

FLAVORS =	python3
FLAVOR ?=	python3

.include <bsd.port.mk>
