SUBDIR =
SUBDIR += binutils
SUBDIR += gcc-bootstrap
SUBDIR += newlib
SUBDIR += gcc-linaro
SUBDIR += binutils,aarch64
SUBDIR += gcc-bootstrap,aarch64
SUBDIR += newlib,aarch64
SUBDIR += gcc-linaro,aarch64
SUBDIR += gdb,arm
SUBDIR += gdb,aarch64

.include <bsd.port.subdir.mk>
