# $OpenBSD$

COMMENT =	Socket.IO server

MODPY_EGG_VERSION =	5.3.0

DISTNAME =	python-socketio-${MODPY_EGG_VERSION}
PKGNAME =	${DISTNAME:S/^python-/py-/}

CATEGORIES =	pypi

HOMEPAGE =	http://github.com/miguelgrinberg/python-socketio/

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =	${MODPY_DEFAULT_VERSION_3}

.include <bsd.port.mk>
