# $OpenBSD$

COMMENT =	convert byte count to human readable format

DISTNAME =	Number-Bytes-Human-0.11

CATEGORIES =	sysutils

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

TEST_DEPENDS =		devel/p5-Test-Pod>=1.18 \
			devel/p5-Test-Pod-Coverage>=1.04

PKG_ARCH =		*

.include <bsd.port.mk>
