# $OpenBSD$

COMMENT =	Safely pass data to untrusted environments and back

MODPY_EGG_VERSION =	2.0.1

DISTNAME =	itsdangerous-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://palletsprojects.com/p/itsdangerous/

# unknown license -> 'BSD-3-Clause'
PERMIT_PACKAGE =	unknown license
PERMIT_DISTFILES =	unknown license

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
