# $OpenBSD$

COMMENT =		3D packages for Kicad 5.1.0
V =			5.1.0
DISTNAME =		kicad-packages3D-${V}
CATEGORIES =		cad

HOMEPAGE =		https://github.com/KiCad/kicad-packages3D

MASTER_SITES =		https://github.com/KiCad/kicad-packages3D/archive/${V}/

#CCA4
PERMIT_PACKAGE_CDROM =	Yes

DIST_SUBDIR =		kicad

MODULES =		devel/cmake

.include <bsd.port.mk>
