# $OpenBSD$

V =			5.1.4
COMMENT =		3D packages for Kicad ${V}
DISTNAME =		kicad-packages3D-${V}
CATEGORIES =		cad

HOMEPAGE =		https://github.com/KiCad/kicad-packages3D

MASTER_SITES =		https://github.com/KiCad/kicad-packages3D/archive/${V}/

#CCA4
PERMIT_PACKAGE =	Yes

COMPILER =		ports-clang

MODULES =		devel/cmake

.include <bsd.port.mk>
