# $OpenBSD$

COMMENT =	Read resources from Python packages

MODPY_EGG_VERSION =	5.1.4

DISTNAME =	importlib_resources-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/python/importlib_resources

# unknown license -> 'Apache2'
PERMIT_PACKAGE =	unknown license
PERMIT_DISTFILES =	unknown license

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =	${MODPY_DEFAULT_VERSION_3}

.include <bsd.port.mk>
