# $OpenBSD$

COMMENT =		symbol modules for Kicad 5.0.0
V =			5.0.0
DISTNAME =		kicad-symbols-${V}
CATEGORIES =		cad

HOMEPAGE =		https://github.com/KiCad/kicad-symbols

MASTER_SITES =		https://github.com/KiCad/kicad-symbols/archive/${V}/

#CCA4
PERMIT_PACKAGE_CDROM =	Yes

DIST_SUBDIR =		kicad

MODULES =		devel/cmake

.include <bsd.port.mk>
