# $OpenBSD$

COMMENT =	Compress responses in your Flask app with gzip, deflate or

MODPY_EGG_VERSION =	1.9.0

DISTNAME =	Flask-Compress-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME:L}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/colour-science/flask-compress

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

FLAVORS =	python3
FLAVOR ?=	python3

.include <bsd.port.mk>
