# $OpenBSD$

COMMENT =		a C++11 library for serialization

GH_ACCOUNT =		USCiLab
GH_PROJECT =		cereal
GH_TAGNAME =		v1.3.0

PKGNAME =		${GH_PROJECT}-${GH_TAGNAME:S/v//}

CATEGORIES =		devel

#BSD
PERMIT_PACKAGE =	Yes

# C++11
COMPILER=		base-clang ports-gcc base-gcc
MODULES =		devel/cmake

.include <bsd.port.mk>
