# $OpenBSD$

COMMENT =	Parse gdb machine interface output with Python

MODPY_EGG_VERSION =	0.10.0.1

DISTNAME =	pygdbmi-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/cs01/pygdbmi

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =	${MODPY_DEFAULT_VERSION_3}

.include <bsd.port.mk>
