# $OpenBSD$

COMMENT =	check the README when running tests

MODPY_EGG_VERSION =	2.7.0

DISTNAME =	pytest-checkdocs-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/jaraco/pytest-checkdocs

# license field not set, consider bugging module's author
PERMIT_PACKAGE =	unknown license
PERMIT_DISTFILES =	unknown license

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =	${MODPY_DEFAULT_VERSION_3}

.include <bsd.port.mk>
