# $OpenBSD$

V =			0.56
COMMENT =		document translations maintainer
DISTNAME =		po4a-${V}
CATEGORIES =		lang

HOMEPAGE =		https://po4a.org/index.php.en

MASTER_SITES =		https://github.com/mquinson/po4a/releases/download/v0.56/

#CCA3 and GPLv3 (dual licensed)
PERMIT_PACKAGE =	Yes

BUILD_DEPENDS =		devel/p5-Module-Build \
			devel/p5-Unicode-GCString

.include <bsd.port.mk>
