# $OpenBSD$

COMMENT =	Validate configuration and produce human readable error

MODPY_EGG_VERSION =	3.3.0

DISTNAME =	cfgv-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/asottile/cfgv

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =	${MODPY_DEFAULT_VERSION_3}

.include <bsd.port.mk>
